# Generated by Django 5.0.6 on 2026-07-11 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('modelo_compatible', models.CharField(blank=True, max_length=120)),
                ('existencias', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refacción',
                'verbose_name_plural': 'Refacciones',
                'db_table': 'refacciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de orden',
                'verbose_name_plural': 'Tipos de orden',
                'db_table': 'tipos_orden',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('estatus', models.CharField(choices=[('ABIERTA', 'Abierta'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABIERTA', max_length=12)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], db_index=True, default='MEDIA', max_length=8)),
                ('descripcion_problema', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='equipment.equipo')),
                ('mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='maintenance.mantenimiento')),
                ('tecnico_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'db_table': 'ordenes_trabajo',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RefaccionUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refacciones_utilizadas', to='workorders.ordentrabajo')),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='workorders.refaccion')),
            ],
            options={
                'verbose_name': 'Refacción utilizada',
                'verbose_name_plural': 'Refacciones utilizadas',
                'db_table': 'refacciones_utilizadas',
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='refacciones',
            field=models.ManyToManyField(blank=True, related_name='ordenes', through='workorders.RefaccionUtilizada', to='workorders.refaccion'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='workorders.tipoorden'),
        ),
        migrations.AddConstraint(
            model_name='refaccionutilizada',
            constraint=models.UniqueConstraint(fields=('orden', 'refaccion'), name='uniq_refaccion_por_orden'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['tecnico_asignado', 'estatus'], name='ordenes_tra_tecnico_834781_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['equipo', '-creado_en'], name='ordenes_tra_equipo__487796_idx'),
        ),
    ]
