# Generated by Django 5.0.6 on 2026-07-11 14:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_historicalequipo_lecturacontador'),
        ('maintenance', '0002_historicalmantenimiento_planmantenimiento'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrdenTrabajo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('folio', models.CharField(db_index=True, editable=False, max_length=20)),
                ('estatus', models.CharField(choices=[('ABIERTA', 'Abierta'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABIERTA', max_length=12)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], db_index=True, default='MEDIA', max_length=8)),
                ('descripcion_problema', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.equipo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mantenimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maintenance.mantenimiento')),
                ('tecnico_asignado', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'rol': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workorders.tipoorden')),
            ],
            options={
                'verbose_name': 'historical Orden de trabajo',
                'verbose_name_plural': 'historical Órdenes de trabajo',
                'db_table': 'auditoria_ordenes_trabajo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
