# Generated by Django 5.0.6 on 2026-07-11 00:58

import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=200)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual de equipo'), ('REPORTE', 'Reporte escaneado'), ('GUIA', 'Guía rápida'), ('OTRO', 'Otro')], db_index=True, max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('modelo_equipo', models.CharField(blank=True, db_index=True, help_text='Modelo Kyocera al que aplica el manual (si no está ligado a un equipo específico).', max_length=80)),
                ('backend_almacenamiento', models.CharField(choices=[('LOCAL', 'Almacenamiento local'), ('ALFRESCO', 'Alfresco ECM')], default='LOCAL', max_length=10)),
                ('archivo', models.FileField(blank=True, help_text='PDF en almacenamiento local (backend LOCAL).', null=True, upload_to=apps.documents.models.ruta_documento, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('referencia_externa', models.CharField(blank=True, help_text='nodeRef/ID del documento en el ECM (backend ALFRESCO).', max_length=255)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='equipment.equipo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
