# Generated by Django 5.0.6 on 2026-07-11 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='workorders.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo', 'modelo_equipo'], name='documentos_tipo_b67fd6_idx'),
        ),
    ]
