# Generated by Django 5.0.6 on 2026-07-12 04:54

import apps.documents.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, help_text='PDF o imagen (evidencias) en almacenamiento local (backend LOCAL).', null=True, upload_to=apps.documents.models.ruta_documento, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('MANUAL', 'Manual de equipo'), ('REPORTE', 'Reporte escaneado'), ('GUIA', 'Guía rápida'), ('EVIDENCIA', 'Evidencia de trabajo'), ('OTRO', 'Otro')], db_index=True, max_length=10),
        ),
    ]
