# Generated by Django 5.0.6 on 2026-07-11 00:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('piso', models.CharField(blank=True, max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'ordering': ['sucursal__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'Solo letras, números y guiones.')])),
                ('modelo', models.CharField(db_index=True, max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuera de servicio'), ('BAJA', 'Dado de baja')], db_index=True, default='OPERATIVO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('contador_paginas', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ubicacion_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='equipment.area')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'ordering': ['numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='HistorialUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('area_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_equipo', to='equipment.area')),
                ('area_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_equipo', to='equipment.area')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_ubicaciones', to='equipment.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de ubicación',
                'verbose_name_plural': 'Historial de ubicaciones',
                'db_table': 'historial_ubicaciones',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='equipment.sucursal'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado', 'modelo'], name='equipos_estado_65cad2_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['ubicacion_actual'], name='equipos_ubicaci_e94a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='historialubicacion',
            index=models.Index(fields=['equipo', '-fecha_movimiento'], name='historial_u_equipo__1db8e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nombre'), name='uniq_area_por_sucursal'),
        ),
    ]
