# Generated by Django 5.0.6 on 2026-07-11 14:39

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_modelo_equipo_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEquipo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_serie', models.CharField(db_index=True, max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'Solo letras, números y guiones.')])),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuera de servicio'), ('BAJA', 'Dado de baja')], db_index=True, default='OPERATIVO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('contador_paginas', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.modeloequipo')),
                ('ubicacion_actual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.area')),
            ],
            options={
                'verbose_name': 'historical Equipo',
                'verbose_name_plural': 'historical Equipos',
                'db_table': 'auditoria_equipos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LecturaContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura', models.PositiveIntegerField()),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='equipment.equipo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de contador',
                'verbose_name_plural': 'Lecturas de contador',
                'db_table': 'lecturas_contador',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['equipo', '-fecha'], name='lecturas_co_equipo__89bba4_idx')],
            },
        ),
    ]
