# Generated by Django 5.0.6 on 2026-07-11 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], db_index=True, max_length=12)),
                ('estatus', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado')], db_index=True, default='PROGRAMADO', max_length=14)),
                ('fecha_programada', models.DateTimeField(db_index=True)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('observaciones_tecnico', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='equipment.equipo')),
                ('tecnico_asignado', models.ForeignKey(limit_choices_to={'rol': 'TECNICO'}, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimientos',
                'ordering': ['fecha_programada'],
                'indexes': [models.Index(fields=['tecnico_asignado', 'fecha_programada'], name='mantenimien_tecnico_f51385_idx'), models.Index(fields=['estatus', 'fecha_programada'], name='mantenimien_estatus_3daaaa_idx'), models.Index(fields=['equipo', '-fecha_programada'], name='mantenimien_equipo__0a357f_idx')],
            },
        ),
    ]
