-- ============================================================================
-- Plataforma de Mantenimiento de Equipos Kyocera
-- Esquema de referencia PostgreSQL 15+
--
-- NOTA: La fuente de verdad del esquema son las migraciones de Django
-- (back/apps/*/models.py → python manage.py migrate). Este DDL documenta la
-- estructura resultante para DBAs y revisión de arquitectura.
-- ============================================================================

CREATE DATABASE kyocera_mantenimiento
    WITH ENCODING 'UTF8'
    LC_COLLATE = 'es_MX.UTF-8'
    LC_CTYPE   = 'es_MX.UTF-8'
    TEMPLATE   = template0;

\c kyocera_mantenimiento;

-- ----------------------------------------------------------------------------
-- 1. USUARIOS Y ROLES
-- ----------------------------------------------------------------------------
CREATE TABLE usuarios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password        VARCHAR(128) NOT NULL,           -- hash PBKDF2 (Django)
    last_login      TIMESTAMPTZ,
    is_superuser    BOOLEAN NOT NULL DEFAULT FALSE,
    username        VARCHAR(150) NOT NULL UNIQUE,
    first_name      VARCHAR(150) NOT NULL DEFAULT '',
    last_name       VARCHAR(150) NOT NULL DEFAULT '',
    email           VARCHAR(254) NOT NULL DEFAULT '',
    is_staff        BOOLEAN NOT NULL DEFAULT FALSE,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    date_joined     TIMESTAMPTZ NOT NULL DEFAULT now(),
    rol             VARCHAR(10) NOT NULL DEFAULT 'TECNICO'
                    CHECK (rol IN ('ADMIN', 'TECNICO')),
    telefono        VARCHAR(20) NOT NULL DEFAULT '',
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_usuarios_rol        ON usuarios (rol);
CREATE INDEX idx_usuarios_rol_activo ON usuarios (rol, is_active);

-- ----------------------------------------------------------------------------
-- 2. CATÁLOGO DE UBICACIONES
-- ----------------------------------------------------------------------------
CREATE TABLE sucursales (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(120) NOT NULL UNIQUE,
    direccion       VARCHAR(255) NOT NULL DEFAULT '',
    ciudad          VARCHAR(100) NOT NULL DEFAULT '',
    activa          BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE areas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id     BIGINT NOT NULL REFERENCES sucursales(id) ON DELETE RESTRICT,
    nombre          VARCHAR(120) NOT NULL,
    piso            VARCHAR(30) NOT NULL DEFAULT '',
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uniq_area_por_sucursal UNIQUE (sucursal_id, nombre)
);
CREATE INDEX idx_areas_sucursal ON areas (sucursal_id);

-- ----------------------------------------------------------------------------
-- 3. EQUIPOS KYOCERA
-- ----------------------------------------------------------------------------
CREATE TABLE equipos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_serie        VARCHAR(50) NOT NULL UNIQUE,
    modelo              VARCHAR(80) NOT NULL,
    descripcion         TEXT NOT NULL DEFAULT '',
    estado              VARCHAR(20) NOT NULL DEFAULT 'OPERATIVO'
                        CHECK (estado IN ('OPERATIVO','EN_MANTENIMIENTO','FUERA_DE_SERVICIO','BAJA')),
    ubicacion_actual_id BIGINT REFERENCES areas(id) ON DELETE RESTRICT,
    fecha_instalacion   DATE,
    contador_paginas    INTEGER NOT NULL DEFAULT 0 CHECK (contador_paginas >= 0),
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_equipos_modelo        ON equipos (modelo);
CREATE INDEX idx_equipos_estado        ON equipos (estado);
CREATE INDEX idx_equipos_estado_modelo ON equipos (estado, modelo);
CREATE INDEX idx_equipos_ubicacion     ON equipos (ubicacion_actual_id);

CREATE TABLE historial_ubicaciones (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id         BIGINT NOT NULL REFERENCES equipos(id) ON DELETE CASCADE,
    area_origen_id    BIGINT REFERENCES areas(id) ON DELETE SET NULL,
    area_destino_id   BIGINT NOT NULL REFERENCES areas(id) ON DELETE RESTRICT,
    motivo            VARCHAR(255) NOT NULL DEFAULT '',
    registrado_por_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    fecha_movimiento  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_hist_ubic_equipo_fecha ON historial_ubicaciones (equipo_id, fecha_movimiento DESC);
CREATE INDEX idx_hist_ubic_fecha        ON historial_ubicaciones (fecha_movimiento);

-- ----------------------------------------------------------------------------
-- 4. MANTENIMIENTOS (CALENDARIO)
-- ----------------------------------------------------------------------------
CREATE TABLE mantenimientos (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id             BIGINT NOT NULL REFERENCES equipos(id) ON DELETE RESTRICT,
    tipo                  VARCHAR(12) NOT NULL CHECK (tipo IN ('PREVENTIVO','CORRECTIVO')),
    estatus               VARCHAR(14) NOT NULL DEFAULT 'PROGRAMADO'
                          CHECK (estatus IN ('PROGRAMADO','EN_PROCESO','COMPLETADO','CANCELADO','REPROGRAMADO')),
    tecnico_asignado_id   BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    fecha_programada      TIMESTAMPTZ NOT NULL,
    fecha_inicio_real     TIMESTAMPTZ,
    fecha_fin_real        TIMESTAMPTZ,
    descripcion           TEXT NOT NULL DEFAULT '',
    observaciones_tecnico TEXT NOT NULL DEFAULT '',
    creado_por_id         BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_fechas_reales CHECK (
        fecha_fin_real IS NULL OR fecha_inicio_real IS NULL
        OR fecha_fin_real >= fecha_inicio_real
    )
);
-- Consulta principal del calendario: por técnico y rango de fechas
CREATE INDEX idx_mant_tecnico_fecha ON mantenimientos (tecnico_asignado_id, fecha_programada);
CREATE INDEX idx_mant_estatus_fecha ON mantenimientos (estatus, fecha_programada);
CREATE INDEX idx_mant_equipo_fecha  ON mantenimientos (equipo_id, fecha_programada DESC);

-- ----------------------------------------------------------------------------
-- 5. ÓRDENES DE TRABAJO
-- ----------------------------------------------------------------------------
CREATE TABLE tipos_orden (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(255) NOT NULL DEFAULT '',
    activo      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE refacciones (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            VARCHAR(50) NOT NULL UNIQUE,
    nombre            VARCHAR(150) NOT NULL,
    modelo_compatible VARCHAR(120) NOT NULL DEFAULT '',
    existencias       INTEGER NOT NULL DEFAULT 0 CHECK (existencias >= 0),
    creado_en         TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE ordenes_trabajo (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio                VARCHAR(20) NOT NULL UNIQUE,
    tipo_id              BIGINT NOT NULL REFERENCES tipos_orden(id) ON DELETE RESTRICT,
    equipo_id            BIGINT NOT NULL REFERENCES equipos(id) ON DELETE RESTRICT,
    tecnico_asignado_id  BIGINT REFERENCES usuarios(id) ON DELETE RESTRICT,
    mantenimiento_id     BIGINT REFERENCES mantenimientos(id) ON DELETE SET NULL,
    estatus              VARCHAR(12) NOT NULL DEFAULT 'ABIERTA'
                         CHECK (estatus IN ('ABIERTA','ASIGNADA','EN_PROCESO','CERRADA','CANCELADA')),
    prioridad            VARCHAR(8) NOT NULL DEFAULT 'MEDIA'
                         CHECK (prioridad IN ('BAJA','MEDIA','ALTA','URGENTE')),
    descripcion_problema TEXT NOT NULL,
    diagnostico          TEXT NOT NULL DEFAULT '',
    trabajo_realizado    TEXT NOT NULL DEFAULT '',
    fecha_cierre         TIMESTAMPTZ,
    creado_por_id        BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ot_tecnico_estatus ON ordenes_trabajo (tecnico_asignado_id, estatus);
CREATE INDEX idx_ot_equipo_creacion ON ordenes_trabajo (equipo_id, creado_en DESC);
CREATE INDEX idx_ot_estatus         ON ordenes_trabajo (estatus);
CREATE INDEX idx_ot_prioridad       ON ordenes_trabajo (prioridad);
CREATE INDEX idx_ot_creado_en       ON ordenes_trabajo (creado_en);

CREATE TABLE refacciones_utilizadas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id      BIGINT NOT NULL REFERENCES ordenes_trabajo(id) ON DELETE CASCADE,
    refaccion_id  BIGINT NOT NULL REFERENCES refacciones(id) ON DELETE RESTRICT,
    cantidad      INTEGER NOT NULL DEFAULT 1 CHECK (cantidad > 0),
    comentario    VARCHAR(255) NOT NULL DEFAULT '',
    registrado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uniq_refaccion_por_orden UNIQUE (orden_id, refaccion_id)
);

-- ----------------------------------------------------------------------------
-- 6. REPOSITORIO DOCUMENTAL (metadatos; binario local o en ECM/Alfresco)
-- ----------------------------------------------------------------------------
CREATE TABLE documentos (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo                 VARCHAR(200) NOT NULL,
    tipo                   VARCHAR(10) NOT NULL CHECK (tipo IN ('MANUAL','REPORTE','GUIA','OTRO')),
    descripcion            TEXT NOT NULL DEFAULT '',
    equipo_id              BIGINT REFERENCES equipos(id) ON DELETE SET NULL,
    modelo_equipo          VARCHAR(80) NOT NULL DEFAULT '',
    orden_trabajo_id       BIGINT REFERENCES ordenes_trabajo(id) ON DELETE SET NULL,
    backend_almacenamiento VARCHAR(10) NOT NULL DEFAULT 'LOCAL'
                           CHECK (backend_almacenamiento IN ('LOCAL','ALFRESCO')),
    archivo                VARCHAR(100),          -- ruta relativa en MEDIA_ROOT
    referencia_externa     VARCHAR(255) NOT NULL DEFAULT '',  -- nodeRef en Alfresco
    tamano_bytes           BIGINT NOT NULL DEFAULT 0,
    version                VARCHAR(20) NOT NULL DEFAULT '1.0',
    subido_por_id          BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    creado_en              TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_doc_titulo       ON documentos (titulo);
CREATE INDEX idx_doc_tipo_modelo  ON documentos (tipo, modelo_equipo);
CREATE INDEX idx_doc_creado_en    ON documentos (creado_en);

-- ----------------------------------------------------------------------------
-- 7. NOTIFICACIONES (relación genérica a mantenimientos / órdenes)
-- ----------------------------------------------------------------------------
CREATE TABLE notificaciones (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    tipo            VARCHAR(15) NOT NULL CHECK (tipo IN ('ASIGNACION','CAMBIO_ESTATUS','SISTEMA')),
    titulo          VARCHAR(150) NOT NULL,
    mensaje         TEXT NOT NULL,
    leida           BOOLEAN NOT NULL DEFAULT FALSE,
    content_type_id INTEGER,                     -- FK a django_content_type
    object_id       BIGINT,
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notif_destinatario ON notificaciones (destinatario_id, leida, creado_en DESC);
